import { Theme } from "common.slint";

export component PreviewWindow inherits Window {
    in property <string> preview-text;

    no-frame: true;
    always-on-top: true;
    background: transparent;
    width: 240px;
    height: 300px;
    title: "预览";
    default-font-family: "Microsoft YaHei UI";

    Rectangle {
        x: 6px;
        y: 6px;
        width: parent.width - 12px;
        height: Math.min(parent.height - 12px, txt.preferred-height + 24px);
        background: Theme.preview-bg;
        border-radius: 12px;
        drop-shadow-blur: 24px;
        drop-shadow-color: #00000045;
        clip: true;

        txt := Text {
            x: 14px;
            y: 12px;
            width: parent.width - 28px;
            text: root.preview-text;
            color: Theme.preview-text;
            font-size: 12.5px;
            wrap: word-wrap;
        }
    }
}
